tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

#
brew "vim"
brew "tmux"
brew "zsh"
brew "fzf"

#
brew "exiftool"
brew "hunspell"

#
cask "visual-studio-code"
cask "clion"
cask "pycharm"

#
cask "authy"
cask "docker"
cask "github"
cask "iterm2"
cask "mactex"
cask "mendeley"
cask "slack"
cask "transmit"
