tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

#
brew "macvim"
brew "tmux"
brew "zsh"

#
brew "boost"
brew "cmake"
brew "exiftool"
brew "hunspell"

#
brew "anyenv"
brew "autoconf"
brew "pkg-config"

#
cask "atom"
cask "visual-studio-code"
cask "clion"
cask "pycharm"

#
cask "authy"
cask "docker"
cask "github"
cask "iterm2"
cask "mactex"
cask "mendeley"
cask "slack"
cask "transmit"
