tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "exiftool"

brew "fzf"
brew "tmux"
brew "vim"
brew "zsh"

cask "clion"
cask "pycharm"
cask "visual-studio-code"

cask "github"
cask "docker"
cask "google-cloud-sdk"
cask "transmit"

cask "adobe-acrobat-reader"
cask "authy"
cask "google-chrome"
cask "iterm2"
cask "mactex"
cask "mendeley"
cask "slack"